### ISSUE TITLE
Ambigious Error while trying to upload whilst offline

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#10]
Currently when I try to take a screenshot without an internet connection this error message occurs:
<img src="https://i.pitter.us/7Gn1w.png"/>
Instead of producing this error, Pitter should instead temporarily save the file to a local directory to then upload to Pitter when the user re-gains internet connection. With this solution the user can continue to easily take screen-shots and save documents with the knowledge that the data is safe.
This is particularly an issue in more remote places (like New Zealand :P) that have very spotty internet connections. Sometimes things appear on your screen only for a second that need quick reactions. It is not very helpful to use this second to take a screenshot only to get an error and lose the data.

PS I did not personally lose any data in this way, I just think that it is likely to happen to somebody in the future.

**Comment by Elycin** [comment]
I'll probably have to write some form of internal checking of the state of the network connections.
Ambiguous errors are the least-likely and unhanded exception of which that messages states that it could not upload to the servers as you said your internet was disconnected.

Although this isn't exactly an issue, I could definitely parse it better on which I'll get to shortly.

Thanks.

**Comment by Elycin** [comment]
Internet Connections are now checked.
