### ISSUE TITLE
Feature request: More obvious offline file storing

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#11]
This feature relates somewhat to the previous issue of attempting offline file uploads.
It would be really helpful if there was the option to store files on the users local machine as well as on the server so that when there is no internet (or the Pitter server is down) any needed files can still be accessed.

EDIT: Oops my bad, maybe it should be made more obvious that this already happens. I didn't know as I rarely ever go into my local documents. Maybe a settings section will do the trick. With that we could even change the download location?

**Comment by Elycin** [comment]
Files are located in ~/Documents/Pitter/!

~ = User Home Directory

**Comment by Elycin** [comment]
Since the change of this ticket, I've implemented the feature today of opening the save directory from the tray icon. Hopefully this should make it easier.
![dgtoj 1](https://cloud.githubusercontent.com/assets/1078382/18175710/491240d0-7040-11e6-930c-43c3018179e5.png)
