### ISSUE TITLE
Uploading copied HTML code gives result rather than raw code

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#12]
Currently when the user has any html code on their clipboard and uses Ctrl+Shift+5, Pitter uploads it just fine as a text document, however when the file is opened via the desktop client or with the newly given link, the browser just shows the result of the code. The only way that I would know to retrieve the raw code is by using the browsers 'view source' option. I am using Edge but I have also tested this in Chrome and Internet Explorer with the same result. This is not a biggie but it is a nuisance nonetheless.

As an example I had this code on my clipboard:
`<iframe src="https://embed.spotify.com/?uri=spotify%3Aartist%3A6s2dMwgwAtGlU9tzNGvS3d" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>` (A Spotify embed code)
and this is the result: https://i.pitter.us/z7GE.txt

**Comment by Elycin** [comment]
This should be worked out soon in the new storage system.

**Comment by Elycin** [comment]
Should be fixed.
