### ISSUE TITLE
Image uploading as jpg and only displaying non-human-readable symbols

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#4]
Using the default window selection tool from the taskbar menu uploads a file with the .jpg extension when it is set to upload a png. On opening of the file it does not display an image:
<img width="687" alt="capture" src="https://cloud.githubusercontent.com/assets/19882546/16871466/27195458-4adb-11e6-900d-b592993914d3.PNG">
This was repeated twice on the secondary monitor with the same results but then on the primary monitor it did display the correct image but was still a jpg. After this test another few selections from both monitors displayed correctly (still as a jpg).

EDIT: After many more file uploads images did eventually start to upload as pngs.

**Comment by Elycin** [comment]
Totally aware of this now, 
Currently waiting out the subject of pitter's providers to install a kernel module so we can write a better request system, which should fix this bug.

Thanks for reporting!
