### ISSUE TITLE
Closing Pitter shows tiny window that cannot be closed

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#5]
<img width="97" alt="capture" src="https://cloud.githubusercontent.com/assets/19882546/16871763/e845fae0-4adc-11e6-9b9c-b63b4036d468.PNG">
When Pitter is opened from the desktop shortcut and then closed, the window seems to go go away until you look in the bottom left corner of the primary screen. This window cannot be closed by the X button. When Pitter is opened from the taskbar and then closed, the window does not appear.

**Comment by Elycin** [comment]
It's an odd bug we've spotted, however clicking the icon on the tray should open it, and if you close it again will remove it from that state.

**Comment by Elycin** [comment]
Good riddance.
