### ISSUE TITLE
Incorrect grandmar in error message

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#7]
<img width="365" alt="pitter" src="https://cloud.githubusercontent.com/assets/19882546/17312449/e16edf16-58a6-11e6-91bd-b54efdd4bc52.png">
Pls remove the rogue apostrophe. (servers not server's)

**Comment by Elycin** [comment]
things happen when you get tired I guess.
Will fix shortly.
