### ISSUE TITLE
No back button in desktop client

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#8]
While going through the Pitter desktop client I found a link taking me to the GitHub issue tracker, so I followed it and then saw an issue: the only way to get back to the main Panel was by pressing the backspace key. I tried this solution only because I had noticed that Pitter's desktop client acts like a web-browser, however most users would not observe this and thus be stuck, since exiting and reopening Pitter just lands you on the same page. This problem could be easily (I think) solved by adding a back button (and possibly forward) to the desktop client.

**Comment by Elycin** [comment]
Fixed.
