### ISSUE TITLE
Images open in Internet Explorer

### ISSUE THREAD

**Issue by NicholasBatesNZ** [Elycin/Pitter-Desktop-Client#9]
<img width="440" alt="pitter" src="https://cloud.githubusercontent.com/assets/19882546/17474816/0b9c6088-5dac-11e6-9c34-d5dae80fc229.PNG">
Currently clicking on image links in the Desktop Panel opens it up in an Internet Explorer window, it would be great if instead it opened in the users default browser or, if that's not possible, there could be a settings option to choose which browser that the image opens in. Also a bigger window would be nice too :)

**Comment by Elycin** [comment]
External links attached with the _blank attribute now open in default browser as of commit d081b98

**Comment by NicholasBatesNZ** [comment]
This issue was closed in the past as the issue was solved, however as of a recent commit it is back for some users thus this ticket should be reopened

**Comment by Elycin** [comment]
I've tested this issue on three machines today with synchronized settings, and all have opened in chrome which is my default browser.
Can you make sure that internet explorer isn't overriding?

**Comment by NicholasBatesNZ** [comment]
Yeah just to be doubly sure I have given all defaults that I could to edge and Firefox and it still opens in IE
